# ============================================================================
# REGLES DE RECOMMANDATION (source = ce notebook ; exportees en CSV editable)
#   colonnes : attributs_similaire | complement_categories |
#              complement_categories_toutes | complement_mots_cles |
#              exclure_mots_cles  (NOUVEAU : blackliste de complements)
# IMPORTANT : REGEN_RULES=True reecrit toujours le CSV depuis _DEFAULT_RULES.
#   -> Pour personnaliser : edite _DEFAULT_RULES ci-dessous, puis re-execute a partir de l'Etape 5.
# ============================================================================
REGEN_RULES = True
RULES_CSV = Path("regles_recommandation.csv")

_DEFAULT_RULES = [
 {"categorie":"batterie","attributs_similaire":"form_factor;chemistry","complement_categories":"chargeur;composant;mecanique;connectique","complement_categories_toutes":"chargeur","complement_mots_cles":"bms;protection;support;porte pile;boitier;holder;chargeur;18650;module charge","exclure_mots_cles":"diode;triac;mosfet;transistor;resistance;condensateur;foret;projecteur;capteur;relais;moteur;ruban led","exemple":"18650 -> chargeur 18650 / BMS / support (jamais diode/TRIAC)"},
 {"categorie":"chargeur","attributs_similaire":"chemistry;connector","complement_categories":"batterie;connectique","complement_categories_toutes":"batterie","complement_mots_cles":"batterie;pile;accu;18650;lipo;li-ion;cellule","exclure_mots_cles":"foret;vis;peinture;moteur","exemple":"Chargeur 18650 -> cellules 18650"},
 {"categorie":"led","attributs_similaire":"led_form;voltage_bucket","complement_categories":"alimentation;electronique;connectique","complement_categories_toutes":"","complement_mots_cles":"alimentation;transformateur;controleur;dimmer;connecteur ruban;profile;amplificateur rgb;bande;ruban","exclure_mots_cles":"foret;vis;peinture;moteur;capteur;fpga;altera;cyclone;diode;projecteur;ramps;reprap;imprimante;creality;ender;incubateur;temperature","exemple":"Ruban LED 12V -> alim 12V / controleur RGB 12V"},
 {"categorie":"alimentation","attributs_similaire":"voltage_bucket;connector","complement_categories":"carte;connectique;led;electronique;mecanique","complement_categories_toutes":"","complement_mots_cles":"raspberry;arduino;esp32;micro sd;carte memoire;boitier;dissipateur;ruban led;ruban;jack","exclure_mots_cles":"foret;vis;peinture;cle;douille;fpga;altera;cyclone;diode;triac;projecteur;domino","exemple":"Alim 5V Raspberry -> Raspberry / carte SD / boitier / dissipateur"},
 {"categorie":"carte","attributs_similaire":"board;connectivity","complement_categories":"capteur;connectique;alimentation;led;electronique;composant","complement_categories_toutes":"capteur","complement_mots_cles":"breadboard;plaque essai;dupont;jumper;cable usb;micro sd;carte memoire;ecran;oled;lcd;afficheur;capteur;alimentation;boitier;dissipateur;relais","exclure_mots_cles":"foret;perceuse;vis;cle;douille;peinture;disjoncteur;fpga;altera;cyclone;visseuse;clé à chocs","exemple":"Arduino/ESP -> capteurs / dupont / alim / ecran"},
 {"categorie":"capteur","attributs_similaire":"sensor","complement_categories":"carte;connectique;electronique","complement_categories_toutes":"carte","complement_mots_cles":"arduino;esp32;raspberry;dupont;jumper;breadboard;resistance;ecran;lcd;oled;module;relais","exclure_mots_cles":"foret;perceuse;vis;cle;peinture;fpga;altera;cyclone;clé à chocs;projecteur","exemple":"Capteur DHT11/PIR -> carte MCU / dupont / ecran"},
 {"categorie":"moteur","attributs_similaire":"motor;voltage_bucket","complement_categories":"carte;electronique;alimentation;batterie;mecanique","complement_categories_toutes":"","complement_mots_cles":"driver;l298;a4988;controleur;esc;arduino;esp32;roue;helice;batterie;lipo;alimentation;servo;pont en h","exclure_mots_cles":"foret;perceuse;vis;peinture;clé à chocs;cle a choc;visseuse;disqueuse;meuleuse;fpga;temperature;humidite;garage;incubateur","exemple":"Moteur -> driver L298/ESC / carte / batterie"},
 {"categorie":"mobilite","attributs_similaire":"vehicle;control","complement_categories":"batterie;moteur;capteur;electronique;connectique;chargeur;rf","complement_categories_toutes":"moteur","complement_mots_cles":"telecommande;radiocommande;roue;helice;chassis;lipo;li-ion;18650;nimh;driver;l298;controleur;esc;ultrason;hc-sr04;suiveur;dupont;moteur;servo;recepteur","exclure_mots_cles":"foret;vis;peinture;cle;douille;perceuse;enceinte;haut parleur;lora;audio;jack;fpga;nema;cnc;industriel;graisse;gonfleur;temperature;humidite;garage;incubateur","exemple":"Voiture RC -> moteur / driver / batterie / capteur ultrason"},
 {"categorie":"rf","attributs_similaire":"rftech","complement_categories":"carte;alimentation;connectique","complement_categories_toutes":"","complement_mots_cles":"arduino;esp32;raspberry;antenne;dupont;module;carte sim;adaptateur","exclure_mots_cles":"foret;vis;haut parleur;enceinte;fpga;altera;peinture","exemple":"NRF24/LoRa/433 -> carte MCU / antenne / dupont"},
 {"categorie":"electronique","attributs_similaire":"module_fn","complement_categories":"carte;connectique;composant;alimentation","complement_categories_toutes":"","complement_mots_cles":"arduino;raspberry;esp32;nano;uno;dupont;breadboard;resistance;potentiometre;support;afficheur;ecran;lcd;oled;capteur","exclure_mots_cles":"foret;perceuse;vis;cle;douille;peinture;fpga;altera;cyclone;projecteur;clé à chocs","exemple":"Relais/LCD/Module -> Arduino / dupont / resistance / afficheur"},
 {"categorie":"composant","attributs_similaire":"component","complement_categories":"electronique;connectique;carte","complement_categories_toutes":"","complement_mots_cles":"breadboard;plaque essai;dupont;resistance;support;arduino;esp32;led;afficheur;potentiometre","exclure_mots_cles":"foret;perceuse;vis;peinture;fpga;altera;cyclone;projecteur;clé à chocs","exemple":"Resistance/diode -> breadboard / dupont / support DIP"},
 {"categorie":"connectique","attributs_similaire":"connector","complement_categories":"carte;electronique;composant","complement_categories_toutes":"","complement_mots_cles":"arduino;raspberry;esp32;module;breadboard;capteur;ecran;led;afficheur","exclure_mots_cles":"foret;vis;peinture;cle;douille;fpga;altera","exemple":"Cable dupont -> carte / module / breadboard"},
 {"categorie":"mesure","attributs_similaire":"","complement_categories":"composant;connectique","complement_categories_toutes":"","complement_mots_cles":"sonde;electrode;pince;cable;cordon;fusible;pile 9v;crocodile","exclure_mots_cles":"foret;vis;peinture;arduino;esp32;fpga","exemple":"Multimetre -> sondes / cordons / pinces"},
 {"categorie":"soudure","attributs_similaire":"","complement_categories":"soudure;composant;connectique","complement_categories_toutes":"","complement_mots_cles":"etain;flux;panne;tresse;pompe a dessouder;troisieme main;decapant","exclure_mots_cles":"foret;perceuse;vis;arduino;esp32;fpga;fer a souder;poste soudure;masque","exemple":"Fer a souder -> etain / flux / panne (consommables)"},
 {"categorie":"solaire","attributs_similaire":"voltage_bucket","complement_categories":"batterie;alimentation;chargeur","complement_categories_toutes":"","complement_mots_cles":"batterie;controleur;mppt;regulateur;18650;lipo;onduleur","exclure_mots_cles":"foret;vis;peinture;fpga;arduino","exemple":"Panneau solaire -> regulateur MPPT / batterie"},
 {"categorie":"audio","attributs_similaire":"","complement_categories":"connectique;alimentation;chargeur","complement_categories_toutes":"","complement_mots_cles":"jack;aux;cable;chargeur;alimentation;support;amplificateur;haut parleur;micro;rca","exclure_mots_cles":"foret;vis;esp32;arduino;relais;fpga;capteur;ruban","exemple":"Enceinte BT -> cable jack / ampli / alim"},
 {"categorie":"outillage","attributs_similaire":"","complement_categories":"","complement_categories_toutes":"","complement_mots_cles":"","exclure_mots_cles":"","exemple":"Outil -> aucun complement IoT"},
 {"categorie":"mecanique","attributs_similaire":"","complement_categories":"","complement_categories_toutes":"","complement_mots_cles":"","exclure_mots_cles":"","exemple":"Boitier/vis -> aucun complement direct (sert aux cartes)"},
 {"categorie":"electrique","attributs_similaire":"","complement_categories":"","complement_categories_toutes":"","complement_mots_cles":"","exclure_mots_cles":"","exemple":"Disjoncteur/220V -> aucun complement IoT"},
]
if REGEN_RULES or not RULES_CSV.exists():
    pd.DataFrame(_DEFAULT_RULES).to_csv(RULES_CSV, index=False)
    print(f"Regles ecrites dans {RULES_CSV}  (REGEN_RULES={REGEN_RULES})")

_rules = pd.read_csv(RULES_CSV).fillna("")
def _spl(s): return [x.strip() for x in str(s).split(";") if x.strip()]

TYPE_ATTRIBUTES     = {r["categorie"]: _spl(r["attributs_similaire"])          for _,r in _rules.iterrows() if _spl(r["attributs_similaire"])}
COMPLEMENTARITY_MAP = {r["categorie"]: _spl(r["complement_categories"])        for _,r in _rules.iterrows() if _spl(r["complement_categories"])}
COMPLEMENT_BROAD    = {r["categorie"]: _spl(r["complement_categories_toutes"]) for _,r in _rules.iterrows()}
COMPLEMENT_KEYWORDS = {r["categorie"]: [normalize_text(k) for k in _spl(r["complement_mots_cles"])] for _,r in _rules.iterrows()}
COMPLEMENT_EXCLUDE  = {r["categorie"]: [normalize_text(k) for k in _spl(r.get("exclure_mots_cles",""))] for _,r in _rules.iterrows()}

print(f"OK Regles chargees -- {len(_rules)} categories (avec blackliste)")
_rules[["categorie","complement_mots_cles","exclure_mots_cles"]].head(6)
